# ¿Qué son las listas?

Una lista es una estructura de datos en la que puedes añadir elementos para su posterior uso. Como en otros lenguajes de programación, las listas permiten guardar cualquier tipo de dato, ya sea enteros, cadenas, objetos e incluso otras listas.

Inicializar una lista
Para declarar una lista vacía se puede hacer con list() o con [].

In [ ]:
my_list = list()
my_list = []

También podemos crear una lista con información predefinida:

In [ ]:
my_list = list([7,6,3,4])
my_list2 = ['a', 'x', 'd']

Para obtener el valor de una posición en concreto deberemos escribir el nombre de la lista, abrir corchetes, poner el número de la posición donde se encuentra el dato que queremos obtener y cerrar corchete. Para obtener el primer elemento la posición sería la número 0, para el segundo valor la posición número 1 y así sucesivamente.

In [ ]:
my_list = list([7,6,3,4])

# Mostrará el primer valor de la lista que es 7
print(my_list[0])

# Mostrará el segundo valor de la lista que es 6
print(my_list[1])

7
6

En el caso de querer recorrer todos los valores de una lista podemos hacerlo con el bucle for.

In [ ]:
my_list = [7, 5, 9, 2, 3, 4]

for value in my_list:
    print(value)

7
5
9
2
3
4

In [ ]:
#Veamos algunos ejemplos mas!
otralista = ["manzana", "banana", "cherry"]
print(otralista)

['manzana', 'banana', 'cherry']

In [ ]:
#Importante las listas aceptan valores duplicados!
otralista_2 = ["manzana", "banana", "cherry", "manzana"]
print(otralista_2)

['manzana', 'banana', 'cherry', 'manzana']

In [ ]:
type(otralista_2)

list

In [ ]:
#Acceso a los datos!
otralista_3 = ["uvas", "banana", "cherry"]
print(otralista_3[0])
print(otralista_3[1])
print(otralista_3[-1])

uvas
banana
cherry

In [ ]:
#Acceso a ciertos elementos de la lista
otralista_4 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(otralista_4[2:5])
print(otralista_4[:4])
print(otralista_4[2:])
print(otralista_4[-4:-1])

['cherry', 'orange', 'kiwi']
['apple', 'banana', 'cherry', 'orange']
['cherry', 'orange', 'kiwi', 'melon', 'mango']
['orange', 'kiwi', 'melon']

In [ ]:
#Veamos algo un poquito mas avanzado
otralista_5 = ["manzana", "banana", "cherry"]
if "manzana" in otralista_5:
  print("Si, la fruta manzana se encuentra en la lista")

Si, la fruta manzana se encuentra en la lista

**Operaciones disponibles para la manipulación de listas**

Si quieres añadir un elemento a la última posición de la lista lo haríamos con el método append.

In [ ]:
#Primero recordemos que teniamos en my_list
my_list

[7, 5, 9, 2, 3, 4]

In [ ]:
my_list.append('hello')
# Después de esto el contenido de la lista será [7, 5, 9, 2, 3, 4, 'hello']

In [ ]:
my_list

[7, 5, 9, 2, 3, 4, 'hello']

En caso de que queramos añadir un elemento en una posición en concreto usaremos el método insert donde el primer parámetro será la posición y el segundo el dato a insertar.

In [ ]:
my_list = list([7,6,3,4,5])
my_list.insert(3, 'test')
print(my_list)
# Ahora el valor de la lista es [7, 6, 3, 'test', 4, 5]

[7, 6, 3, 'test', 4, 5]

Al hacer esto, el valor que estaba en esa posición y los siguientes se desplazarán una posición.

Cuando queramos sustituir el valor de una posición en concreto deberemos escribir el nombre de la lista, abrir corchetes y añadir la posición del dato que queremos reemplazar, cerramos corchetes, escribimos igual y ya añadimos el valor que le queramos dar.

In [ ]:
my_list = list([7,6,3,4,5])

my_list[1] = 4

print(my_list)
# Ahora el valor de la lista es [7, 4, 3, 4, 5]

[7, 4, 3, 4, 5]

In [ ]:
#Veamos otro ejemplo mas!
ejemplo_lista = ["manzana", "banana", "cherry", "naranja", "kiwi", "mango"]

In [ ]:
ejemplo_lista

['manzana', 'banana', 'cherry', 'naranja', 'kiwi', 'mango']

In [ ]:
ejemplo_lista[1:3] = ["uvas", "cerezas"]
print(ejemplo_lista)

['manzana', 'uvas', 'cerezas', 'naranja', 'kiwi', 'mango']

En este caso hemos sustituido el valor 6 que estaba en la posición uno de la lista por 4.

Si queremos eliminar un elemento que conozcamos su valor usaremos remove, en el caso de que esté repetido el valor pasado por parámetro, solo borraría el primer ítem que encontrase:

In [ ]:
my_list = [7, 4, 3, 4, 5]

my_list.remove(4)

print(my_list)
# Print: [7, 3, 4, 5]

[7, 3, 4, 5]

Al ejecutar este código solo elimina el primer valor igual a 4, el segundo y si hubiera más se mantendrían.

En el caso de que lo queramos hacer por clave usaremos su posición en la lista con el método pop, si no pasamos un parámetro, eliminará el valor guardado en la última posición:

In [ ]:
my_list = ['z', 'x', 'm', 'r', 'b']

my_list.pop(2)

print(my_list)
# Print: ['z', 'x', 'r', 'b']
my_list.pop()

print(my_list)
# Print: ['z', 'x', 'r']

['z', 'x', 'r', 'b']
['z', 'x', 'r']

Para unir listas podemos usar el operador + como se ve en el siguiente ejemplo, esto nos devolverá una nueva lista con los elementos de las otras dos listas.

In [ ]:
my_list = ['x']
my_list2 = ['m', 'c', 'r']
my_list3 = my_list + my_list2
print(my_list3)
# Print: ['x', 'm', 'c', 'r']

['x', 'm', 'c', 'r']

Para repetir los elementos de una lista usaremos el operador * sobre la lista en la que queramos multiplicar sus valores.

In [ ]:
my_list = ['d']
my_list_x_5 = my_list * 5
print(my_list_x_5)

['d', 'd', 'd', 'd', 'd']

Si queremos invertir el orden de una lista lo haremos como en el siguiente ejemplo.

In [ ]:
my_list = [1, 2, 3, 4, 5]
my_list_reversed = my_list[::-1]
print(my_list_reversed)
# Print: [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]

En el caso de que queramos ordenar la lista utilizaremos el método sort, que ordenará nuestra lista de forma ascendente.

In [ ]:
my_list = [2,1,5,4,3]
my_list.sort()
print(my_list)
# Print: [1,2,3,4,5]

[1, 2, 3, 4, 5]

In [ ]:
my_list.sort(reverse = True)
print(my_list)

[5, 4, 3, 2, 1]

Si queremos vaciar una lista, podemos utilizar el método clear().

In [ ]:
my_list = [2,1,5,4,3]
my_list.clear()
print(my_list)
# Print: []

[]

# TUPLAS

Son similares a las listas, pero lo que las diferencia es que estas son inmutables, esto quiere decir que no puede modificarse de ninguna forma después de su creación.

Se pueden definir de estas dos formas:

In [ ]:
my_tuple = (1,2,3,4)

# También de esta forma

my_tuple = tuple((1, 2, 3, 4))

Para acceder a un valor dada una posición lo haremos igual que con las listas, escribiendo el nombre de la tupla seguido de apertura de corchetes, posición que buscamos y cierre de corchetes:

In [ ]:
my_tuple = tuple(('x', 'b', 'm', 'r'))
print(my_tuple[1])
# Print: b

b

In [ ]:
mi_tupla = ("manzana", "banana", "cherry", "manzana", "cherry")
print(mi_tupla)

('manzana', 'banana', 'cherry', 'manzana', 'cherry')

In [ ]:
#Veamos la funcion len()
print(len(mi_tupla))

5

In [ ]:
type(mi_tupla)

tuple

In [ ]:
#Otro ejemplo mas!
tuple1 = ("abc", 99, True, 40, "femenino")
tuple1

('abc', 99, True, 40, 'femenino')

In [ ]:
#Tambien podemos acceder a la tupla de atras hacia adelante
print(tuple1[-1])

femenino

In [ ]:
#y por rango
print(tuple1[2:5])

(True, 40, 'femenino')

In [ ]:
print(tuple1[:4])

('abc', 99, True, 40)

In [ ]:
print(tuple1[2:])

(True, 40, 'femenino')

Las tuplas no se pueden cambiar , por lo que no puede eliminar elementos, pero puede usar la misma solución alternativa que usamos para cambiar y agregar elementos de tupla:

In [ ]:
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)

In [ ]:
thistuple

('banana', 'cherry')

In [ ]:
#Con la funcion del podemos eliminar una tupla por completo!
thistuple = ("apple", "banana", "cherry")
del thistuple
print(thistuple)

NameError: name 'thistuple' is not defined

In [ ]:
#Las tuplas tambien se pueden iterar :)
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

In [ ]:
# y joinear
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)

In [ ]:
#Tuplas multiples
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)